<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>yuuki_krita_helper</text>
        <Action name="pykrita_yuuki_krita_helper_trigger_color_selector123">
            <icon/>
            <text>Open Resources Folder</text>
            <whatsThis>Opens a file browser at the location Krita saves resources such as brushes to.</whatsThis>
            <toolTip>Opens a file browser at the location Krita saves resources such as brushes to.</toolTip>
            <iconText>Open Resources Folder</iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut/>
            <isCheckable>false</isCheckable>
            <statusTip/>
        </Action>
    </Actions>
</ActionCollection>

<!-----
    user guide:
        https://docs.krita.org/en/user_manual/python_scripting/krita_python_plugin_howto.html
    save this file in below location:
        Windows: C:\Users\%USERNAME%\AppData\Roaming\krita\actions\
        Linux: $HOME/.local/share/krita/actions/
----->
